# Generated by Django 4.0.4 on 2022-05-19 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationForm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerform',
            name='address',
        ),
        migrations.RemoveField(
            model_name='registerform',
            name='cellular_phone',
        ),
        migrations.RemoveField(
            model_name='registerform',
            name='city',
        ),
        migrations.RemoveField(
            model_name='registerform',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='registerform',
            name='infected_before',
        ),
        migrations.RemoveField(
            model_name='registerform',
            name='land_line',
        ),
        migrations.RemoveField(
            model_name='registerform',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='registerform',
            name='zip_code',
        ),
    ]
